site_name: MATRIX
site_description: MATRIX OS Documentation
docs_dir: docs
theme_dir: matrix
pages:
- Getting Started: 'index.md'
- Upgrades: 'upgrades.md'
- MATRIX CLI:
  - 'MATRIX CLI': 'CLI/overview.md'
  - 'Installation': 'CLI/installation.md'
  - 'Apps': 'CLI/apps.md'
  - 'Devices': 'CLI/device.md'
  - 'Examples': 'CLI/example.md'
  - 'Troubleshooting': 'intro/cli-troubleshooting.md'
- MATRIX OS:
  - MATRIX OS: 'API/overview.md'
  - App Publishing: 'intro/app-publishing.md'
  - App API:
    - 'Sensors': 'API/sensors.md'
    - 'Everloop': 'API/everloop.md'
    - 'Filters': 'API/filter.md'
    - 'Computer Vision': 'API/computer-vision.md'
    - 'Microphone': 'API/microphone.md'
    - 'Cross-Talk': 'API/crosstalk.md'
    - 'Type': 'API/typesend.md'
    - 'GPIO': 'API/GPIO.md'
    - 'IR TX/RX': 'API/ir.md'
    - 'NFC': 'API/nfc.md'
    - 'Z-wave': 'API/zwave.md'
    - 'Zigbee': 'API/zigbee.md'
    - 'Servos': 'API/servos.md'
    - 'File Storage': 'API/file-storage.md'
    - 'Local Database': 'API/db.md'
  - Configuration:
    - 'Settings': 'API/settings.md'
    - 'Overview': 'Configuration/overview.md'
    - 'Datatypes': 'Configuration/datatypes.md'
    - 'Screens': 'Configuration/screens.md'
    - 'Filters': 'Configuration/filters.md'
    - 'Widgets': 'Configuration/widgets.md'
    - 'Services': 'Configuration/services.md'
    - 'Config File': 'Configuration/example-config.md'
    - 'Widget Examples': 'Configuration/examples.md'
  - Troubleshooting: 'intro/matrix-troubleshooting.md'
- Hardware:
  - 'Hardware': 'Hardware/overview.md'
  - 'Creator': 'Reference/creator.md'
  - 'Voice': 'Reference/voice.md'
  - HAL:
    - 'Examples': 'HAL/examples.md'
    - 'Troubleshooting': 'HAL/troubleshooting.md'
  - MALOS:
    - 'Overview': 'MALOS/overview.md'
    - 'Examples': 'MALOS/example.md'
    - 'Troubleshooting': 'MALOS/troubleshooting.md'
  - 'Pinout': 'Reference/pinout.md'
  - 'FPGA': 'Hardware/fpga.md'
  - 'SAM3': 'Hardware/Sam3.md'
  - 'SAM3MCU': 'Hardware/sam3mcu-programming.md'
  - 'Microphone': 'Hardware/microphone.md'
  - 'SPI': 'Hardware/SPI.md'
- Demos:
  - 'Alexa on Creator': 'Demos/Alexa.md'
- Dictionary: 'dictionary.md'
