site_name: MATRIX
site_description: MATRIX Documentation
docs_dir: docs
theme_dir: matrix
pages:
- Overview: 'index.md'
- Device Setup: 'setup.md'
- MATRIX Applications:
  # Index pages are hidden by template, child[0].url is loaded when user clicks on category
  - 'Index': 'matrix-os/index.md'
  - 'Getting Started':
    - 'Prerequisities': 'matrix-os/getting-started/prerequisites.md'
    - 'Mobile Pairing' : 'matrix-os/getting-started/pairing.md' 
    - 'Installation': 'matrix-os/getting-started/installation.md'
    - 'Hello World': 'matrix-os/getting-started/hello-world.md'
    - 'Next Steps': 'matrix-os/getting-started/next-steps.md'
  - 'Overview':
    - 'Index': 'matrix-os/overview/index.md'
    - 'Applications' : 'matrix-os/overview/applications.md'
    - 'Dashboard': 'matrix-os/overview/dashboard.md'
    - 'Configuration' : 'matrix-os/overview/configuration.md'
    - 'Command Line Interface': 'matrix-os/overview/cli.md'
    - 'Sending Data': 'matrix-os/overview/data.md'
    - 'Publishing': 'matrix-os/overview/publishing.md'
    - 'Manual Setup': 'matrix-os/overview/manual-setup.md'
  - Examples:
    - 'Index': 'matrix-os/examples/index.md'
    - 'Create an App': 'matrix-os/examples/app-create.md'
    - 'Create an Dashboard': 'matrix-os/examples/dash-create.md'
    - 'Sensor Test' : 'matrix-os/examples/sensor-test.md'
    - 'IFTTT Integration' : 'matrix-os/examples/ifttt.md'
  - Reference:
    - 'Index': 'matrix-os/reference/index.md'
    - 'System': 'matrix-os/reference/system.md'
    - 'Sensors': 'matrix-os/reference/sensors.md'
    - 'Computer Vision': 'matrix-os/reference/computer-vision.md'
    - 'Leds': 'matrix-os/reference/leds.md'
    - 'Crosstalk': 'matrix-os/reference/crosstalk.md'
    - 'Zigbee': 'matrix-os/reference/zigbee.md'
    - 'GPIO': 'matrix-os/reference/gpio.md'
    - 'IR': 'matrix-os/reference/ir.md'
    - 'Microphone': 'matrix-os/reference/microphone.md'
    - 'Integrations': 'matrix-os/reference/integrations.md'
    - 'Filters' : 'matrix-os/reference/filters.md'
    - 'Screens' : 'matrix-os/reference/screens.md'
    - 'Widgets': 'matrix-os/reference/widgets.md'
  - Troubleshooting: 'matrix-os/troubleshooting.md'
- MATRIX CORE:
  - 'Index': 'matrix-core/index.md'
  - 'Getting Started':
    - 'Prerequisities': 'matrix-core/getting-started/prerequisites.md'
    - 'Installation': 'matrix-core/getting-started/installation.md'
    - 'Hello World': 'matrix-core/getting-started/hello-world.md'
  - Examples:
    - 'Python' : 'matrix-core/examples/tests.md'
  - Reference:
    - 'Sensors': 'matrix-core/reference/sensors.md'
    - 'Communication': 'matrix-core/reference/communication.md'
    - 'Microphone': 'matrix-core/reference/microphone.md'
  - Troubleshooting: 'matrix-core/troubleshooting.md'
- MATRIX HAL:
  - 'Index': 'matrix-hal/index.md'
  - 'Getting Started':
    - 'Installation': 'matrix-hal/getting-started/installation.md'
    - 'Hello World': 'matrix-hal/getting-started/hello-world.md'
    - 'Next Steps': 'matrix-hal/getting-started/next-steps.md'
  - Boards:
    - 'Creator': 'matrix-hal/datasheets/creator.md'
    - 'Voice': 'matrix-hal/datasheets/voice.md'
  - Components:
    - 'FPGA': 'matrix-hal/components/fpga.md'
    - 'Microphone': 'matrix-hal/components/microphone.md'
    - 'SAM3': 'matrix-hal/components/Sam3.md'
    - 'SAM3MCU': 'matrix-hal/components/Sam3mcu.md'
    - 'Pinout': 'matrix-hal/components/pinout.md'
    - 'SPI': 'matrix-hal/components/SPI.md'
  - Tools:
    - 'OpenOCD': 'matrix-hal/tools.md'
    - 'xc3sprog': 'matrix-hal/tools.md'
  - Examples:
    - 'Alexa' : 'matrix-hal/examples/alexa.md'
  - Troubleshooting: 'matrix-hal/troubleshooting.md'
- Support : 'help.md'
#   - App Publishing: 'intro/app-publishing.md'
#   - App API:
#     - 'Sensors': 'API/sensors.md'
#     - 'Everloop': 'API/everloop.md'
#     - 'Filters': 'API/filter.md'
#     - 'Computer Vision': 'API/computer-vision.md'
#     - 'Microphone': 'API/microphone.md'
#     - 'Cross-Talk': 'API/crosstalk.md'
#     - 'Type': 'API/typesend.md'
#     - 'GPIO': 'API/GPIO.md'
#     - 'IR TX/RX': 'API/ir.md'
#     - 'NFC': 'API/nfc.md'
#     - 'Z-wave': 'API/zwave.md'
#     - 'Zigbee': 'API/zigbee.md'
#     - 'Servos': 'API/servos.md'
#     - 'File Storage': 'API/file-storage.md'
#     - 'Local Database': 'API/db.md'
#   - Configuration:
#     - 'Settings': 'API/settings.md'
#     - 'Overview': 'Configuration/overview.md'
#     - 'Datatypes': 'Configuration/datatypes.md'
#     - 'Screens': 'Configuration/screens.md'
#     - 'Filters': 'Configuration/filters.md'
#     - 'Widgets': 'Configuration/widgets.md'
#     - 'Services': 'Configuration/services.md'
#     - 'Config File': 'Configuration/example-config.md'
#     - 'Widget Examples': 'Configuration/examples.md'
#   - Troubleshooting: 'intro/matrix-troubleshooting.md'
# - Hardware:
#   - 'Hardware': 'Hardware/overview.md'
#   - 'Creator': 'Reference/creator.md'
#   - 'Voice': 'Reference/voice.md'
#   - HAL:
#     - 'Examples': 'HAL/examples.md'
#     - 'Troubleshooting': 'HAL/troubleshooting.md'
#   - MALOS:
#     - 'Overview': 'MALOS/overview.md'
#     - 'Examples': 'MALOS/example.md'
#     - 'Troubleshooting': 'MALOS/troubleshooting.md'
#   - 'Pinout': 'Reference/pinout.md'
#   - 'FPGA': 'Hardware/fpga.md'
#   - 'SAM3': 'Hardware/Sam3.md'
#   - 'SAM3MCU': 'Hardware/sam3mcu-programming.md'
#   - 'Microphone': 'Hardware/microphone.md'
#   - 'SPI': 'Hardware/SPI.md'
# - Demos:
#   - 'Alexa on Creator': 'Demos/Alexa.md'
# - Dictionary: 'dictionary.md'
