site_name: MATRIX
site_description: MATRIX Documentation
docs_dir: docs
theme_dir: matrix
pages:
- Overview: 'index.md'
# MATRIX Boards
- MATRIX Creator:
  - 'Overview': 'matrix-creator/overview.md'
  - 'Device Setup': 'matrix-creator/device-setup.md'
  - Resources:
    - 'Overview': 'matrix-creator/resources/overview.md'
    - 'Pinout': 'matrix-creator/resources/pinout.md'
    - 'Microphone': 'matrix-creator/resources/microphone.md'
    - 'Reference Models': 'matrix-creator/resources/reference-models.md'
    - 'System Architecture': 'matrix-creator/resources/system-architecture.md'
    - 'Technical Datasheets': 'matrix-creator/resources/technical-datasheets.md'
- MATRIX Voice:
  - 'Overview': 'matrix-voice/overview.md'
  - 'Device Setup': 'matrix-voice/device-setup.md'
  - 'ESP32': 'matrix-voice/esp32.md'
  - Resources:
    - 'Overview': 'matrix-voice/resources/overview.md'
    - 'Pinout': 'matrix-voice/resources/pinout.md'
    - 'Microphone': 'matrix-voice/resources/microphone.md'
    - 'Reference Models': 'matrix-voice/resources/reference-models.md'
    - 'System Architecture': 'matrix-voice/resources/system-architecture.md'
    - 'Technical Datasheets': 'matrix-voice/resources/technical-datasheets.md'
# Ecosystem
- MATRIX OS:
  # Index pages are hidden by template, child[0].url is loaded when user clicks on category
  - 'Overview': 'matrix-os/overview.md'
  - Getting Started:
      - 'Index': 'matrix-os/getting-started/index.md'
      - 'Installation': 'matrix-os/getting-started/installation.md'
      - 'Applications': 'matrix-os/getting-started/applications.md'
      - 'Publishing Apps': 'matrix-os/getting-started/publishing.md'
  - Reference:
    - 'Index': 'matrix-os/reference/index.md'
    - 'Sensors': 'matrix-os/reference/sensors.md'
    - 'Everloop': 'matrix-os/reference/leds.md'
    #- 'Filters' : 'matrix-os/reference/filters.md'
    - 'Computer Vision': 'matrix-os/reference/computer-vision.md'
    - 'GPIO': 'matrix-os/reference/gpio.md'
    - 'Zigbee': 'matrix-os/reference/zigbee.md'
    # - 'IR': 'matrix-os/reference/ir.md'
    # - 'Microphone': 'matrix-os/reference/microphone.md'
    - 'Configuration': 'matrix-os/reference/configuration.md'
    - 'CLI Tool': 'matrix-os/reference/cli-tool.md'
    - 'Dashboard': 'matrix-os/reference/dashboard.md'
    - 'Widgets': 'matrix-os/reference/widgets.md'
    - 'Corss Talk': 'matrix-os/reference/crosstalk.md'
    - 'Data Types': 'matrix-os/reference/data-types.md'
    - 'System': 'matrix-os/reference/system.md'
    - 'Integrations': 'matrix-os/reference/integrations.md'
  - Examples:
    - 'Examples': 'matrix-os/examples/index.md'
    - 'IFTTT Integration': 'matrix-os/examples/ifttt.md'
    - 'Dashboard': 'matrix-os/examples/dash-create.md'
  - Troubleshooting: 'matrix-os/troubleshooting.md'
- MATRIX CORE:
  - 'MATRIX CORE': 'matrix-core/index.md'
  - 'Getting Started':
    - 'Prerequisities': 'matrix-core/getting-started/prerequisites.md'
    - 'Installation': 'matrix-core/getting-started/installation.md'
    - 'Hello World': 'matrix-core/getting-started/hello-world.md'
    - 'Next Steps': 'matrix-core/getting-started/next-steps.md'
  - Examples:
    - 'Python' : 'matrix-core/examples/pytests.md'
    - 'JavaScript' : 'matrix-core/examples/jstests.md'
  - Reference:
    - 'Index': 'matrix-core/reference/index.md'
    - 'Everloop': 'matrix-core/reference/everloop.md'
    - 'GPIO': 'matrix-core/reference/gpio.md'
    - 'Humidity': 'matrix-core/reference/humidity.md'
    - 'IMU': 'matrix-core/reference/imu.md'
    # - 'IR': 'matrix-core/reference/lirc.md'
    - 'Pressure': 'matrix-core/reference/pressure.md'
    - 'Servo': 'matrix-core/reference/servo.md'
    - 'UV': 'matrix-core/reference/uv.md'
  - Troubleshooting: 'matrix-core/troubleshooting.md'
- MATRIX HAL:
  - 'MATRIX HAL': 'matrix-hal/index.md'
  - 'Getting Started':
    - 'Installation': 'matrix-hal/getting-started/installation.md'
    - 'Hello World': 'matrix-hal/getting-started/hello-world.md'
    - 'Next Steps': 'matrix-hal/getting-started/next-steps.md'
  - Sensor Tests: 'matrix-hal/examples/hardware-demos.md'
- Support : 'help.md'
#   - App Publishing: 'intro/app-publishing.md'
#   - App API:
#     - 'Sensors': 'API/sensors.md'
#     - 'Everloop': 'API/everloop.md'
#     - 'Filters': 'API/filter.md'
#     - 'Computer Vision': 'API/computer-vision.md'
#     - 'Microphone': 'API/microphone.md'
#     - 'Cross-Talk': 'API/crosstalk.md'
#     - 'Type': 'API/typesend.md'
#     - 'GPIO': 'API/GPIO.md'
#     - 'IR TX/RX': 'API/ir.md'
#     - 'NFC': 'API/nfc.md'
#     - 'Z-wave': 'API/zwave.md'
#     - 'Zigbee': 'API/zigbee.md'
#     - 'Servos': 'API/servos.md'
#     - 'File Storage': 'API/file-storage.md'
#     - 'Local Database': 'API/db.md'
#   - Configuration:
#     - 'Settings': 'API/settings.md'
#     - 'Overview': 'Configuration/overview.md'
#     - 'Datatypes': 'Configuration/datatypes.md'
#     - 'Screens': 'Configuration/screens.md'
#     - 'Filters': 'Configuration/filters.md'
#     - 'Widgets': 'Configuration/widgets.md'
#     - 'Services': 'Configuration/services.md'
#     - 'Config File': 'Configuration/example-config.md'
#     - 'Widget Examples': 'Configuration/examples.md'
#   - Troubleshooting: 'intro/matrix-troubleshooting.md'
# - Hardware:
#   - 'Hardware': 'Hardware/overview.md'
#   - 'Creator': 'Reference/creator.md'
#   - 'Voice': 'Reference/voice.md'
#   - HAL:
#     - 'Examples': 'HAL/examples.md'
#     - 'Troubleshooting': 'HAL/troubleshooting.md'
#   - CORE:
#     - 'Overview': 'CORE/overview.md'
#     - 'Examples': 'CORE/example.md'
#     - 'Troubleshooting': 'CORE/troubleshooting.md'
#   - 'Pinout': 'Reference/pinout.md'
#   - 'FPGA': 'Hardware/fpga.md'
#   - 'SAM3': 'Hardware/Sam3.md'
#   - 'SAM3MCU': 'Hardware/sam3mcu-programming.md'
#   - 'Microphone': 'Hardware/microphone.md'
#   - 'SPI': 'Hardware/SPI.md'
# - Demos:
#   - 'Alexa on Creator': 'Demos/Alexa.md'
# - Dictionary: 'dictionary.md'
